### ISSUE TITLE
Feature: User can select a name for their story

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can begin the process of creating their story by entering the name of the story 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be presented with a text field in which they will be able to enter the title of their new story

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210023028-cb9915cb-c21e-4f61-bce8-f531cf842a28.png)
![image](https://user-images.githubusercontent.com/113651780/210023148-6c7039ed-13dc-41ad-9bc8-86efdbe9db6a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component for the html skeleton
- [x] Create a component for the navbar
- [x] Create a component for the hamburger button
- [x] Create a component for the title entry field
- [x] Create a component for the enter button

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
