### ISSUE TITLE
Feature: User can create their own account

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can enter their own login details to create their own account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be presented with a sign up page where they can enter a desired username and password to log in with

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210118709-52980e5b-ab14-4464-a752-6a8b6d882781.png)
![image](https://user-images.githubusercontent.com/113651780/210118727-c1802734-1fa9-4362-a40a-999e0edf5a0d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `data.sql` to push the data of a successful account creation

### ☁️ Server Tasks

- [ ] Update `server/index.js` to handle the submission of a new user's login details
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to show the user the sign up page

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
