### ISSUE TITLE
Feature: User can generate a story based on their entered prompt

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate a story based on the entered prompt

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be presented with a text field to enter the prompt that they will have the AI generate a story based off of

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210023869-80544979-9b10-444b-809e-e63f1da9fd7f.png)
![image](https://user-images.githubusercontent.com/113651780/210023882-19cc8d13-6c26-40f8-9c23-6445ba83da19.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to use the openai node package
- [x] Call the openai method inside of the route that the prompt is sent
- [x] Return the value back to the client
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create prompt.jsx
- [x] Pass the title that the user created to prompt.jsx either as a prop or via the route URL
- [x] Render title of the page as the passed information
- [x] Create a component to have a text field for the user to enter the prompt that they want their story generated off of
- [x] Create a submit button component that will allow the user to submit their prompt to the engine
- [x] Send the prompt and title as an http request to the server

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
