### ISSUE TITLE
Feature: User can preview their story

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can read the story that was generated based on their prompt

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user had clicked the submit button, the story that was created based on their prompt will be displayed on the screen for them to be able to read it in its entirety

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210105759-7de91d25-a37b-4c57-863a-af28c61b0403.png)
![image](https://user-images.githubusercontent.com/113651780/210106232-45f9e3dd-5abe-46dc-ad18-0a573eb1aec6.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive the response from the api
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render the response of the api
- [x] Update component to make sure the title and story are displayed together properly

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
