### ISSUE TITLE
Feature: User can specify any themes and/or writing styles they would like

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

users can customize style or theme of the story

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be presented with an optional textbox to specify themes/styles for the story to be written in/with

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210106811-fb0dc4d5-5536-4ac1-ae59-fb06413aa840.png)
![image](https://user-images.githubusercontent.com/113651780/210106823-547b0e61-34f1-42c6-b83b-bcf12e0d7177.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to concatenate the story prompt with the requested modifiers
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for users to enter modifiers

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
