### ISSUE TITLE
Feature: User can add story to their library

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a story to their library

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will have a button at the bottom of their story view page for them to add the story to their collection (or go back)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210107713-b38a5423-98c7-4755-b1cc-f1848679d5d9.png)
![image](https://user-images.githubusercontent.com/113651780/210107885-fda39532-52a5-407c-99d7-01048a2842c0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create the table for the saved stories
- [x] Update `data.sql` to store each story as a new entry when the user clicks save

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle the save button request
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to allow the user to save the story they are reading
- [x] Create a component that allows the user to delete their entry and start fresh

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
