### ISSUE TITLE
Feature: User can view library of saved stories

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse and open their saved stories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will be presented with a library view page where they can click their story to read it again

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

 
![image](https://user-images.githubusercontent.com/113651780/210117422-70aefe0e-6c66-4bff-a77c-f707280f3cea.png)
![image](https://user-images.githubusercontent.com/113651780/210117432-1c14e509-4047-4df5-b475-22aa4267a57e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to populate client with the entries that are in the db to build the library view page
- [x] Receive request from client about specific story and return that story text to client
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show the library of stories
- [x] allow user to click or tap an entry to bring it up again similar to the preview

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
