### ISSUE TITLE
Feature: User can delete a story from their library

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can delete a story from their library

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will have a delete button under their story when they are reading it that they can click to remove it from their library

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210117734-70196280-5cc2-4519-bd5b-03b749c8be0d.png)
![image](https://user-images.githubusercontent.com/113651780/210117762-c4831a05-6088-42e6-86ae-6572d0d9f45e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `data.sql` to remove the deleted entry

### ☁️ Server Tasks

- [ ] Update `server/index.js` to handle the delete request from the client and remove it from the db
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to display a delete button under the story when they are viewing it from their library
- [ ] also create a back to library button
- [ ] make sure the library is displayed again when they delete a story

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
