### ISSUE TITLE
Feature: User can log into an account

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can log into an account by giving a username and password

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

there will be a login page where the user can type in their login to authenticate themselves

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210118269-4fe0a2f8-7385-490e-8df1-51a86e2fb086.png)
![image](https://user-images.githubusercontent.com/113651780/210118284-6228050f-5296-4e4b-bb6e-64c14d373e87.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to handle a login request and verify it with details in db
- [ ] Handle all errors and respond to the client, reply bad info if bad login

### ⚡ Client Tasks

- [ ] Create a component to display a login screen 
- [ ] block any page from being displayed unless the user is authenticated

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
