### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can log out of the account that they are currently logged into

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click the hamburger button to have the menu pop out
they will then be able to click a log out button and return to the log in page 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113651780/210118596-4ea8c500-3380-4bec-9af2-e7df5890429a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Update component to delete token from client upon logout

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
